# docker-compose.yaml
# 同样遵循严格的缩进
version: '3.1'

services:
  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
      DISABLE_AUTH: "true"

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database

  user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"

  shippy-ui:
    build: ./shippy-ui
    ports:
      - 3000:80
    environment:
      MICRO_REGISTRY: "mdns"

  email-service:
    build: ./email-service
    ports:
      - 50054:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  api:
    command: api --handler=rpc --address=:8080 --namespace=shippy 
    image: microhq/micro
    ports:
      - 8080:8080
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  microweb:
    image: microhq/micro
    command: web --address=:8080 --namespace=shippy 
    ports:
      - "18080:8080"
    environment:
      - MICRO_API_NAMESPACE=shippy
      - MICRO_REGISTRY=mdns

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432

  nats:
    image: nats
    ports:
      - 4222:4222

